### PR TITLE
Update golang syntax to new yed standard

### PR DESCRIPTION
**Pull request by uniquepointer**

### CODE REVIEW

**Comment by kammerdienerb** [comment]
Nice update! A few issues:

1. This plugin highlights C buffers with Go syntax. In the event handler, the filetype check should be changed to check for "GoLang".
2. Remove the `kw` file. It doesn't seem to be used by the plugin.
3. Go doesn't use the `->` operator for fields of a struct that you have a pointer to like C does. It just uses `.`.
4. Go does not have a preprocessor, so the `#if 0` range in with the comment attributes should not be there.
5. Since Go does not have a preprocessor, all of the keywords with `code-preprocessor` should have `code-keyword` instead except for `defer`, which should have `code-control-flow`.

**Comment by uniquepointer** [comment]
Well the reason I decided to put those on the preprocessor it's so they have a different color, if you still think I should remove it, I will.

**Comment by uniquepointer** [comment]
just a temporary push, depending on what you say about preprocessor stuff.

**Comment by kammerdienerb** [comment]
Okay, I understand where you're coming from with the keywords. Keep it how you have it for now, but on the next breaking change, let's add a new style component that will be a better fit for this kind of language element. Perhaps `code-builtin`? I'm open to ideas about that.

**Comment by uniquepointer** [comment]
how about directives? all languages have some sort of "import" or "namespace" style sort of deal that's only to indicate module stuff.

**Comment by kammerdienerb** [comment]
Yeah, I could see that one being useful. I still think `code-builtin` would be good for Go’s `make` or Python’s `Len` for example. Maybe we’ll do both.

**Pull request merged**
